package com.wesai.kotlin.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wesai.kotlin.greenDao.GreenJava;
import com.wesai.kotlin.greenDao.UserDao;

import com.wesai.kotlin.greenDao.GreenJavaDao;
import com.wesai.kotlin.greenDao.UserDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenJavaDaoConfig;
    private final DaoConfig userDaoDaoConfig;

    private final GreenJavaDao greenJavaDao;
    private final UserDaoDao userDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenJavaDaoConfig = daoConfigMap.get(GreenJavaDao.class).clone();
        greenJavaDaoConfig.initIdentityScope(type);

        userDaoDaoConfig = daoConfigMap.get(UserDaoDao.class).clone();
        userDaoDaoConfig.initIdentityScope(type);

        greenJavaDao = new GreenJavaDao(greenJavaDaoConfig, this);
        userDaoDao = new UserDaoDao(userDaoDaoConfig, this);

        registerDao(GreenJava.class, greenJavaDao);
        registerDao(UserDao.class, userDaoDao);
    }
    
    public void clear() {
        greenJavaDaoConfig.clearIdentityScope();
        userDaoDaoConfig.clearIdentityScope();
    }

    public GreenJavaDao getGreenJavaDao() {
        return greenJavaDao;
    }

    public UserDaoDao getUserDaoDao() {
        return userDaoDao;
    }

}
